package com.github.InspiredOne.InspiredNations.Economy;

import java.util.HashMap;

import org.bukkit.inventory.ItemStack;

import com.github.InspiredOne.InspiredNations.InspiredNations;

public class ItemIndexes {

	InspiredNations plugin;
	
	HashMap<ItemStack, Integer> index = new HashMap<ItemStack, Integer>();
	
	public ItemIndexes(InspiredNations instance) {
		plugin = instance;
		
		this.put(1, 0, "Stone");
		this.put(2, 0, "Grass Block");
		this.put(3, 0, "Dirt");
		this.put(4, 0, "Cobblestone");
		this.put(5, 0, "Wooden Plank(Oak)");
		this.put(5, 1, "Wooden Plank(Spruce)");
		this.put(5, 2, "Wooden Plank(Birch)");
		this.put(5, 3, "Wooden Plank(Jungle)");
		this.put(6, 0, "Sapling(Oak)");
		this.put(6, 1, "Sapling(Spruce)");
		this.put(6, 2, "Sapling(Birch)");
		this.put(6, 3, "Sapling(Jungle)");
		this.put(7, 0, "Bedrock");
		this.put(8, 0, "Water");
		this.put(9, 0, "Water (No Spread)");
		this.put(10, 0, "Lava");
		this.put(11, 0, "Lava (No Spread)");
		this.put(12, 0, "Sand");
		this.put(13, 0, "Gravel");
		this.put(14, 0, "Gold Ore");
		this.put(15, 0, "Iron Ore");
		this.put(16, 0, "Coal Ore");
		this.put(17, 0, "Wood (Oak)");
		this.put(17, 1, "Wood (Spruce)");
		this.put(17, 2, "Wood (Birch)");
		this.put(17, 3, "Wood (Jungle)");
		this.put(18, 0, "Leaves (Oak)");
		this.put(18, 1, "Leaves (Spruce)");
		this.put(18, 2, "Leaves (Birch)");
		this.put(18, 3, "Leaves (Jungle)");
		this.put(19, 0, "Sponge");
		this.put(20, 0, "Glass");
		this.put(21, 0, "Lapis Lazuli Ore");
		this.put(22, 0, "Lapis Lazuli Block");
		this.put(23, 0, "Dispenser");
		this.put(24, 0, "Sandstone");
		this.put(24, 1, "Sandstone (Chiseled)");
		this.put(24, 2, "Sandstone (Smooth)");
		this.put(25, 0, "Note Block");
		this.put(26, 0, "Bed (Block)");
		this.put(27, 0, "Rail (Powered)");
		this.put(28, 0, "Rail (Detector)");
		this.put(29, 0, "Sticky Piston");
		this.put(30, 0, "Cobweb");
		this.put(31, 0, "Tall Grass (Dead Shrub)");
		this.put(31, 1, "Tall Grass");
		this.put(31, 2, "Tall Grass (Fern)");
		this.put(32, 0, "Dead Shrub");
		this.put(33, 0, "Piston");
		this.put(34, 0, "Piston (Head)");
		this.put(35, 0, "Wool");
		this.put(35, 1, "Orange Wool");
		this.put(35, 2, "Magenta Wool");
		this.put(35, 3, "Light Blue Wool");
		this.put(35, 4, "Yellow Wool");
		this.put(35, 5, "Lime Wool");
		this.put(35, 6, "Pink Wool");
		this.put(35, 7, "Gray Wool");
		this.put(35, 8, "Light Gray Wool");
		this.put(35, 9, "Cyan Wool");
		this.put(35, 10, "Purple Wool");
		this.put(35, 11, "Blue Wool");
		this.put(35, 12, "Brown Wool");
		this.put(35, 13, "Green Wool");
		this.put(35, 14, "Red Wool");
		this.put(35, 15, "Black Wool");
		this.put(36, 0, "Piston (Moving)");
		this.put(37, 0, "Dandelion");
		this.put(38, 0, "Rose");
		this.put(39, 0, "Brown Mushroom");
		this.put(40, 0, "Red Mushroom");
		this.put(41, 0, "Block Of Gold");
		this.put(42, 0, "Block Of Iron");
		this.put(43, 0, "Stone Slab (Double)");
		this.put(43, 1, "Sandstone Slab (Double)");
		this.put(43, 2, "Wooden Slab (Double)");
		this.put(43, 3, "Cobblestone Slab (Double)");
		this.put(43, 4, "Brick Slab (Double)");
		this.put(43, 5, "Stone Brick Slab (Double)");
		this.put(43, 6, "Nether Brick Slab (Double)");
		this.put(43, 7, "Quartz Slab (Double)");
		this.put(43, 8, "Smooth Stone Slab (Double)");
		this.put(43, 9, "Smooth Sandstone Slab (Double)");
		this.put(44, 0, "Stone Slab");
		this.put(44, 1, "Sandstone Slab");
		this.put(44, 2, "Wooden Slab");
		this.put(44, 3, "Cobblestone Slab");
		this.put(44, 4, "Brick Slab");
		this.put(44, 4, "Stone Brick Slab");
		this.put(44, 6, "Nether Brick Slab");
		this.put(44, 7, "Quartz Slab");
		this.put(45, 0, "Brick");
		this.put(46, 0, "TNT");
		this.put(47, 0, "Bookcase");
		this.put(48, 0, "Moss Stone");
		this.put(49, 0, "Obsidian");
		this.put(50, 0, "Torch");
		this.put(51, 0, "Fire");
		this.put(52, 0, "Mob Spawner");
		this.put(53, 0, "Wooden Stairs (Oak)");
		this.put(54, 0, "Chest");
		this.put(55, 0, "Redstone Wire");
		this.put(56, 0, "Diamond Ore");
		this.put(57, 0, "Blcok Of Diamond");
		this.put(58, 0, "Workbench");
		this.put(59, 0, "Wheat (Crop)");
		this.put(60, 0, "Farmland");
		this.put(61, 0, "Furnace");
		this.put(62, 0, "Furnace (Smelting)");
		this.put(63, 0, "Sign (Block)");
		this.put(64, 0, "Wood Door (Block)");
		this.put(65, 0, "Ladder");
		this.put(66, 0, "Rail");
		this.put(67, 0, "CobbleStone Stairs");
		this.put(68, 0, "Sign (Wall Block)");
		this.put(69, 0, "Lever");
		this.put(70, 0, "Stone Pressure Plate");
		this.put(71, 0, "Iron Door (Block)");
		this.put(72, 0, "Wooden Pressure Plate");
		this.put(73, 0, "Redstone Ore");
		this.put(74, 0, "Redstone Ore (Glowing)");
		this.put(75, 0, "Redstone Torch (Off)");
		this.put(76, 0, "Redstone Torch");
		this.put(77, 0, "Button (Stone)");
		this.put(78, 0, "Snow");
		this.put(79, 0, "Ice");
		this.put(80, 0, "Snow Block");
		this.put(81, 0, "Cactus");
		this.put(82, 0, "Clay Block");
		this.put(83, 0, "Sugar Cane (Block)");
		this.put(84, 0, "Jukebox");
		this.put(85, 0, "Fence");
		this.put(86, 0, "Pumpkin");
		this.put(87, 0, "Netherrack");
		this.put(88, 0, "Soul Sand");
		this.put(89, 0, "GlowStone");
		this.put(90, 0, "Portal");
		this.put(91, 0, "Jack-O-Lantern");
		this.put(92, 0, "Cake");
		this.put(93, 0, "Redstone Repeater (Block Off)");
		this.put(94, 0, "Redstone Repeater (Block On)");
		this.put(95, 0, "Locked Chest");
		this.put(96, 0, "TrapDoor");
		this.put(97, 0, "Silverfish Stone");
		this.put(97, 1, "Silverfish Cobblestone");
		this.put(97, 2, "Silverfish Stone Brick");
		this.put(98, 0, "Stone Brick");
		this.put(98, 1, "Mossy Stone Brick");
		this.put(98, 2, "Cracked Stone Brick");
		this.put(98, 3, "Chiseled Stone Brick");
		this.put(99, 0, "Brown Mushroom (Block)");
		this.put(100, 0, "Red Mushroom (Block)");
		this.put(101, 0, "Iron Bars");
		this.put(102, 0, "Glass Pane");
		this.put(103, 0, "Melon (Block)");
		this.put(104, 0, "Pumpkin Vine");
		this.put(105, 0, "Melon Vine");
		this.put(106, 0, "Vines");
		this.put(107, 0, "Fence Gate");
		this.put(108, 0, "Brick Stairs");
		this.put(109, 0, "Stone Brick Stairs");
		this.put(110, 0, "Mycelium");
		this.put(111, 0, "Lily Pad");
		this.put(112, 0, "Nether Brick");
		this.put(113, 0, "Nether Brick Fence");
		this.put(114, 0, "Nether Brick Stairs");
		this.put(115, 0, "Nether Wart");
		this.put(116, 0, "Enchantment Table");
		this.put(117, 0, "Brewing Stand (Block)");
		this.put(118, 0, "Cauldron (Block)");
		this.put(119, 0, "End Portal");
		this.put(120, 0, "End Portal Frame");
		this.put(121, 0, "End Stone");
		this.put(122, 0, "Dragon Egg");
		this.put(123, 0, "Redstone Lamp");
		this.put(124, 0, "Redstone Lamp (On)");
		this.put(125, 0, "Oak Slab (Double)");
		this.put(125, 1, "Spruce Slab (Double)");
		this.put(125, 2, "Birch Slab (Double)");
		this.put(125, 3, "Jungle Slab (Double)");
		this.put(126, 0, "Oak Slab");
		this.put(126, 1, "Spruce Slab");
		this.put(126, 2, "Birch Slab");
		this.put(126, 3, "Jungle Slab");
		this.put(127, 0, "Coca Plant");
		this.put(128, 0, "Sandstone Stairs");
		this.put(129, 0, "Emerald Ore");
		this.put(130, 0, "Ender Chest");
		this.put(131, 0, "Tripwire Hook");
		this.put(132, 0, "Trip Wire");
		this.put(133, 0, "Block Of Emerald");
		this.put(134, 0, "Spruce Stairs");
		this.put(135, 0, "Birch Stairs");
		this.put(136, 0, "Jungle Stairs");
		this.put(137, 0, "Command Block");
		this.put(138, 0, "Beacon");
		this.put(139, 0, "Cobblestone Wall");
		this.put(139, 1, "Mossy Cobble Wall");
		this.put(140, 0, "Flower Pot (Block)");
		this.put(141, 0, "Carrot (Crop)");
		this.put(142, 0, "Potatoes (Crop)");
		this.put(143, 0, "Wood Button");
		this.put(144, 0, "Skeleton Head");
		this.put(144, 1, "Wither Head");
		this.put(144, 2, "Zombie Head");
		this.put(144, 3, "Head");
		this.put(144, 4, "Creeper Head");
		this.put(145, 0, "Anvil");
		this.put(145, 1, "Damaged Anvil");
		this.put(145, 2, "Very Damaged Anvil");
		this.put(146, 0, "Trapped Chest");
		this.put(147, 0, "Gold Pressure Plate");
		this.put(148, 0, "Iron Pressure Plate");
		this.put(149, 0, "Redstone Comparator (Off)");
		this.put(150, 0, "Redstone Comparator (On)");
		this.put(151, 0, "Daylight Sensor");
		this.put(152, 0, "Redstone Block");
		this.put(153, 0, "Nether Quartz Ore");
		this.put(154, 0, "Hopper");
		this.put(155, 0, "Quartze Block");
		this.put(155, 1, "Chiseled Quartz");
		this.put(155, 2, "Pillar Quartz");
		this.put(156, 0, "Quartz Stairs");
		this.put(157, 0, "Activator Rail");
		this.put(158, 0, "Dropper");
		this.put(159, 0, "White Clay");
		this.put(159, 1, "Orange Clay");
		this.put(159, 2, "Magenta Clay");
		this.put(159, 3, "Light Blue Clay");
		this.put(159, 4, "Yellow Clay");
		this.put(159, 5, "Lime Clay");
		this.put(159, 6, "Pink Clay");
		this.put(159, 7, "Gray Clay");
		this.put(159, 8, "Light Gray Clay");
		this.put(159, 9, "Cyan Clay");
		this.put(159, 10, "Purple Clay");
		this.put(159, 11, "Blue Clay");
		this.put(159, 12, "Brown Clay");
		this.put(159, 13, "Green Clay");
		this.put(159, 14, "Red Clay");
		this.put(159, 15, "Black Clay");
		this.put(170, 0, "Hay Bale");
	}
	
	public boolean contains(ItemStack item) {
		return index.containsKey(item);
	}
	
	public void put(ItemStack item) {
		index.put(item, index.size());
	}
	
	public void put(int type, int dura, String name) {
		index.put(new ItemStack(type,1,(short) dura), index.size());
	}
	
	public int get(ItemStack item) {
		return index.get(item);
	}
	
}
